// Mocks generated by Mockito 5.0.17 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i10;

import 'package:core/core.dart' as _i2;
import 'package:dartz/dartz.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:search/domain/usecases/search_movies.dart' as _i6;
import 'package:search/domain/usecases/search_tv.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i8;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieRepository_0 extends _i1.Fake implements _i2.MovieRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeTvRepository_2 extends _i1.Fake implements _i2.TvRepository {}

class _FakeMovieDetailResponse_3 extends _i1.Fake
    implements _i2.MovieDetailResponse {}

class _FakeTvDetailResponse_4 extends _i1.Fake implements _i2.TvDetailResponse {
}

class _FakeResponse_5 extends _i1.Fake implements _i4.Response {}

class _FakeStreamedResponse_6 extends _i1.Fake implements _i4.StreamedResponse {
}

/// A class which mocks [GetNowPlayingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingMovies extends _i1.Mock
    implements _i2.GetNowPlayingMovies {
  MockGetNowPlayingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i2.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i2.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i2.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i2.Failure, _i2.MovieDetail>>.value(
              _FakeEither_1<_i2.Failure, _i2.MovieDetail>())) as _i5
          .Future<_i3.Either<_i2.Failure, _i2.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i2.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i2.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetMovieWatchlistStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieWatchlistStatus extends _i1.Mock
    implements _i2.GetMovieWatchlistStatus {
  MockGetMovieWatchlistStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [SaveMovieWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveMovieWatchlist extends _i1.Mock
    implements _i2.SaveMovieWatchlist {
  MockSaveMovieWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> execute(_i2.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
}

/// A class which mocks [RemoveMovieWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveMovieWatchlist extends _i1.Mock
    implements _i2.RemoveMovieWatchlist {
  MockRemoveMovieWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> execute(_i2.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i6.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_0()) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetAiringTodayTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAiringTodayTv extends _i1.Mock implements _i2.GetAiringTodayTv {
  MockGetAiringTodayTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetOnAirTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnAirTv extends _i1.Mock implements _i2.GetOnAirTv {
  MockGetOnAirTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i2.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i2.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i2.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue: Future<_i3.Either<_i2.Failure, _i2.TvDetail>>.value(
                  _FakeEither_1<_i2.Failure, _i2.TvDetail>()))
          as _i5.Future<_i3.Either<_i2.Failure, _i2.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i2.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i2.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [GetTvWatchlistStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvWatchlistStatus extends _i1.Mock
    implements _i2.GetTvWatchlistStatus {
  MockGetTvWatchlistStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [SaveTvWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTvWatchlist extends _i1.Mock implements _i2.SaveTvWatchlist {
  MockSaveTvWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> execute(_i2.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
}

/// A class which mocks [RemoveTvWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTvWatchlist extends _i1.Mock implements _i2.RemoveTvWatchlist {
  MockRemoveTvWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> execute(_i2.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
}

/// A class which mocks [SearchTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTv extends _i1.Mock implements _i7.SearchTv {
  MockSearchTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_2()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> execute(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i3.Either<_i2.Failure, _i2.MovieDetail>>.value(
              _FakeEither_1<_i2.Failure, _i2.MovieDetail>())) as _i5
          .Future<_i3.Either<_i2.Failure, _i2.MovieDetail>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> saveWatchlist(
          _i2.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> removeWatchlist(
          _i2.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>.value(
              _FakeEither_1<_i2.Failure, List<_i2.Movie>>())) as _i5
          .Future<_i3.Either<_i2.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i2.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.MovieModel>> getNowPlayingMovies() => (super.noSuchMethod(
          Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]))
      as _i5.Future<List<_i2.MovieModel>>);
  @override
  _i5.Future<List<_i2.MovieModel>> getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue: Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]))
      as _i5.Future<List<_i2.MovieModel>>);
  @override
  _i5.Future<List<_i2.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
          Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]))
      as _i5.Future<List<_i2.MovieModel>>);
  @override
  _i5.Future<_i2.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i2.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_3()))
          as _i5.Future<_i2.MovieDetailResponse>);
  @override
  _i5.Future<List<_i2.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]))
          as _i5.Future<List<_i2.MovieModel>>);
  @override
  _i5.Future<List<_i2.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]))
          as _i5.Future<List<_i2.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i2.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> removeWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i2.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i2.MovieTable?>.value())
          as _i5.Future<_i2.MovieTable?>);
  @override
  _i5.Future<List<_i2.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
          Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<List<_i2.MovieTable>>.value(<_i2.MovieTable>[]))
      as _i5.Future<List<_i2.MovieTable>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i2.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getAiringTodayTv() =>
      (super.noSuchMethod(Invocation.method(#getAiringTodayTv, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getOnAirTv() =>
      (super.noSuchMethod(Invocation.method(#getOnAirTv, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getTopRatedTv() =>
      (super
              .noSuchMethod(Invocation.method(#getTopRatedTv, []),
                  returnValue:
                      Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                          _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: Future<_i3.Either<_i2.Failure, _i2.TvDetail>>.value(
                  _FakeEither_1<_i2.Failure, _i2.TvDetail>()))
          as _i5.Future<_i3.Either<_i2.Failure, _i2.TvDetail>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> searchTv(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> saveTvWatchlist(
          _i2.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveTvWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> removeTvWatchlist(
          _i2.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i2.Failure, String>>.value(
                  _FakeEither_1<_i2.Failure, String>()))
          as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<bool> tvIsAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#tvIsAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue:
                  Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                      _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>()))
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i2.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.TvModel>> getAiringTodayTv() =>
      (super.noSuchMethod(Invocation.method(#getAiringTodayTv, []),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
  @override
  _i5.Future<List<_i2.TvModel>> getOnAirTv() =>
      (super.noSuchMethod(Invocation.method(#getOnAirTv, []),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
  @override
  _i5.Future<List<_i2.TvModel>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
  @override
  _i5.Future<List<_i2.TvModel>> getTopRatedTv() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTv, []),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
  @override
  _i5.Future<_i2.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue:
                  Future<_i2.TvDetailResponse>.value(_FakeTvDetailResponse_4()))
          as _i5.Future<_i2.TvDetailResponse>);
  @override
  _i5.Future<List<_i2.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
  @override
  _i5.Future<List<_i2.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
              returnValue: Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]))
          as _i5.Future<List<_i2.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i2.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertTvWatchlist(_i2.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> removeTvWatchlist(_i2.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i2.TvTable?> getTvById(int? id) => (super.noSuchMethod(
      Invocation.method(#getTvById, [id]),
      returnValue: Future<_i2.TvTable?>.value()) as _i5.Future<_i2.TvTable?>);
  @override
  _i5.Future<List<_i2.TvTable>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue: Future<List<_i2.TvTable>>.value(<_i2.TvTable>[]))
          as _i5.Future<List<_i2.TvTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i2.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i8.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i8.Database?>.value()) as _i5.Future<_i8.Database?>);
  @override
  _i5.Future<int> insertWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
  @override
  _i5.Future<int> insertTvWatchlist(_i2.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeTvWatchlist(_i2.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_5()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i10.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i10.Uint8List>.value(_i10.Uint8List(0)))
          as _i5.Future<_i10.Uint8List>);
  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_6()))
          as _i5.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
